---

- name: Use molecule to test all roles in the playbook.
  hosts: all
  become: true
  become_user: root
  remote_user: root
  vars:
    update_apt_cache: true
    force_ssh_authentication: false
    ansible_python_interpreter: /usr/bin/python

  roles:
    - security
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx
