---

- name: Create a {{ application_name }} virtual machine via vagrant
  hosts: all
  become: yes
  become_user: root
  remote_user: vagrant
  vars:
    - include_security: false
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/vagrant.yml

  roles:
    - { role: security, when: include_security == true, tags: ['security'] }
    - base
    - db
    - rabbitmq
    - web
    - celery
    - nginx