---

- name: Add authorized_keys for the user
  ansible.posix.authorized_key:
    user: "{{ server_user }}"
    key: "{{ lookup('file', item) }}"
  with_items:
    - "{{ user_public_keys }}"

- name: Disallow password authentication
  ansible.builtin.lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: restart ssh

- name: Allow ssh only for primary user
  ansible.builtin.lineinfile: dest=/etc/ssh/sshd_config
              regexp="^AllowUsers"
              line="AllowUsers {{ server_user }}"
              state=present
  notify: restart ssh
