---

- name: Install Uncomplicated Firewall
  ansible.builtin.apt: update_cache={{ update_apt_cache }} state=present pkg=ufw

  # Allow only ssh and http(s) ports
- name: Allow ssh and http(s) connections
  community.general.ufw: rule=allow port={{ item }}
  with_items:
    - "{{ ufw_allowed_ports }}"

- name: Enable ufw/firewall
  community.general.ufw: state=enabled policy=deny
