---

- name: Install the Avahi mDNS/DNS-SD daemon
  ansible.builtin.apt:
    name: avahi-daemon
    update_cache: "{{ update_apt_cache }}"
    state: present
  tags: packages

- name: Ensure the Avahi mDNS/DNS-SD daemon is running
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: true
