---
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:stream8
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      roles_path: ../../roles
