---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-jammy
    image: ubuntu:jammy
    groups:
      - vagrant
    privileged: true
  - name: instance-focal
    image: ubuntu:focal
    groups:
      - vagrant
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles/
  inventory:
    links:
      group_vars: ../../group_vars/
verifier:
  name: ansible
