---

- name: Install Certbot
  ansible.builtin.apt:
    update_cache: "{{ update_apt_cache }}"
    state: present
    name:
      - certbot
  tags: packages

- name: Check if Nginx exists
  ansible.builtin.stat: path=/etc/init.d/nginx
  register: nginx_status

- name: Ensure Nginx is stopped
  ansible.builtin.service: name=nginx state=stopped
  when: nginx_status.stat.exists

- name: Install certbot and generate cert
  ansible.builtin.command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ inventory_hostname }} -d www.{{ inventory_hostname }}"
  when: multiple_sites is not defined
  args:
    creates: "{{ certbot_output_dir }}"
  ignore_errors: yes

- name: Install certbot and generate cert for multiple sites
  # NOTE: This does not accommodate www. domains.
  # Add -d www.{{ item }} to accommodate these.
  command: "{{ certbot_script }} certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ item }}"
  when: multiple_sites is defined
  with_items: "{{ multiple_sites }}"
  ignore_errors: yes

- name: Ensure Nginx is started
  ansible.builtin.service: name=nginx state=started
  when: nginx_status.stat.exists

- name: Ensure a cron job to auto-renew the cert exists
  ansible.builtin.cron: name="daily auto renew cert"
        special_time=daily
        job="{{ certbot_script }} renew --standalone --no-self-upgrade --pre-hook \"service nginx stop\" --post-hook \"service nginx start\" --quiet"
        state=present
  when: certbot_auto_renew
  tags: notest
