---

git_repo: https://github.com/jcalazan/youtube-audio-dl.git

# Set this flag to true so you can checkout code from a private git repository
# which is setup with an SSH key.
ssh_forward_agent: false

project_name: youtube-audio-dl
application_name: youtubeadl

# Note that this PPA doesn't guarantee timely updates in case of security issues.
# Simply remove these two vars below if you prefer to use the official PPA and
# default Python version that came with your Linux distro.
#
# More info here: https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes
enable_deadsnakes_ppa: true
virtualenv_python_version: python3.6


# Project layout
# The following paths are relative to the root of your project where various
# files can be found.

# The relative path where manage.py can be found. The default is that
# manage.py can be found in the root directory of the project.
django_relative_path: .

# The relative path to the requirements file. The default is that
# requirements.txt can be found in the root directory of the project.
# Override this value in env_vars/vagrant.yml and/or env_vars/development.yml
# if you have different requirements for each environment.
requirements_relative_file: ./requirements_local.txt
