---

- name: Install packages required by the Django app inside virtualenv
  ansible.builtin.pip:
    virtualenv: "{{ virtualenv_path }}"
    requirements: "{{ requirements_file }}"
    extra_args: "{{ pip_use_upgrade_flag | ternary('--upgrade', omit) }}"

- name: Run the Django syncdb command
  community.general.django_manage:
    command: syncdb
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_syncdb is defined and run_django_syncdb
  tags: django.syncdb

- name: Run Django database migrations
  community.general.django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  become: false
  tags:
    - django.migrate
    - deploy

- name: Run Django collectstatic
  community.general.django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  notify: Restart application
  become: false
  tags:
    - django.collectstatic
    - deploy

- name: Ensure a cron job for running minutely jobs exists
  ansible.builtin.cron: name="run minutely jobs"
        minute="*"
        job="bash {{ project_path }}/bin/{{ run_jobs_bash_file }} minutely"
        state=present
  when: run_minutely_jobs is defined and run_minutely_jobs
  tags: django.cron

- name: Ensure a cron job for running hourly jobs exists
  ansible.builtin.cron: name="run hourly jobs"
        minute="15"
        job="bash {{ project_path }}/bin/{{ run_jobs_bash_file }} hourly"
        state=present
  when: run_hourly_jobs is defined and run_hourly_jobs
  tags: django.cron

- name: Ensure a cron job for running daily jobs exists
  ansible.builtin.cron: name="run daily jobs"
        minute="35"
        hour="15"
        job="bash {{ project_path }}/bin/{{ run_jobs_bash_file }} daily"
        state=present
  when: run_daily_jobs is defined and run_daily_jobs
  tags: django.cron

- name: Ensure a cron job for running weekly jobs exists
  ansible.builtin.cron: name="run weekly jobs"
        minute="35"
        hour="9"
        weekday="1"
        job="bash {{ project_path }}/bin/{{ run_jobs_bash_file }} weekly"
        state=present
  when: run_weekly_jobs is defined and run_weekly_jobs
  tags: django.cron

- name: Ensure a cron job for running monthly jobs exists
  ansible.builtin.cron: name="run monthly jobs"
        minute="35"
        hour="10"
        day="1"
        job="bash {{ project_path }}/bin/{{ run_jobs_bash_file }} monthly"
        state=present
  when: run_monthly_jobs is defined and run_monthly_jobs
  tags: django.cron
